mutation userLogin ($email: String!, $password: String!, $rememberMe: Boolean!) {
    userLogin(
        email: $email, 
        password: $password, 
        rememberMe: $rememberMe
    ) {
        id
    }
}